banks:
  allBanks:
    - bankCode: VNPAY
      privateKey: ghffffffffff
      ips:

    - bankCode: BIDV
      privateKey: jjjjjjjj
      ips:

    - bankCode: 970445
      privateKey: abyukmnh
      ips: