banks:
  allBanks:
    - bankCode: VNPAY
      privateKey: ghffffffffff
      ips:

    - bankCode: BIDV
      privateKey: jjjjjjjj
      ips:

    - bankCode: 970445
      privateKey: abyukmnh
      ips:

    - bankCode: 11055
      privateKey: lkjlk
      ips:

server:
  port: 9091

#logging:
#  config: ./config/logback.xml